name: Auto-Merge
on:
  pull_request_target:
    types:
      - labeled

jobs:
  enable-auto-merge:
    runs-on: ubuntu-latest

    if: contains(github.event.pull_request.labels.*.name, 'dependencies') && (github.event.pull_request.user.login == 'matt-sturgeon-ci[bot]' || github.event.pull_request.user.login == 'dependabot[bot]')
    steps:
      - name: Create GitHub App token
        uses: actions/create-github-app-token@v2
        id: app
        with:
          app-id: ${{ vars.MS_APP_ID }}
          private-key: ${{ secrets.MS_APP_PRIVATE_KEY }}
      - name: Enable Auto Merge (rebase)
        uses: alexwilson/enable-github-automerge-action@main
        with:
          github-token: ${{ steps.app.outputs.token }}
          merge-method: REBASE
