name: Check

on:
  workflow_dispatch:  # can be triggered manually
  pull_request:
  push:
    paths-ignore:
      - "LICENSE"
      - "**.md"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install nix
        uses: cachix/install-nix-action@v31
      - name: Setup nix cache
        uses: cachix/cachix-action@v16
        with:
          name: matt-sturgeon
          authToken: ${{ secrets.CACHIX_TOKEN }}
      - name: Run flake checker
        uses: DeterminateSystems/flake-checker-action@main
      - name: Check flake
        run: nix flake check
