name: Check

on:
  workflow_dispatch:  # can be triggered manually
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install nix
        uses: cachix/install-nix-action@v31
      - name: Generate Nix Matrix
        id: set-matrix
        run: |
          set -Eeu
          matrix="$(nix eval --json .#githubActions.matrix)"
          echo "matrix=$matrix" >> "$GITHUB_OUTPUT"

  flake-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install nix
        uses: cachix/install-nix-action@v31
      - name: Run flake checker
        uses: DeterminateSystems/flake-checker-action@main

  build:
    name: ${{ matrix.name }} (${{ matrix.system }})
    needs: build-matrix
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.build-matrix.outputs.matrix) }}
    steps:
      - name: Free disk space
        uses: wimpysworld/nothing-but-nix@main
        with:
          # Options: holster, carve, cleave (default), rampage
          hatchet-protocol: rampage
          # Increase root-safe-haven to 25GB so that build-dir has enough space
          root-safe-haven: '25600' # Default 2048
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install nix
        uses: cachix/install-nix-action@v31
      - name: Setup nix cache
        uses: cachix/cachix-action@v16
        with:
          name: matt-sturgeon
          extraPullNames: nix-community
          authToken: ${{ secrets.CACHIX_TOKEN }}
      - name: Build ${{ matrix.attr }}
        env:
          attr: ${{ matrix.attr }}
        run: |
          nix build ".#$attr" \
              --abort-on-warn \
              --print-build-logs \
              --log-format raw

  # A meta-job that can be referenced by GitHub Rulesets.
  # It is normally skipped, but if there was a failure it will also fail.
  check-success:
    name: Success
    runs-on: ubuntu-latest
    if: failure()
    needs:
      - build
      - flake-checker
    steps:
      - name: Failed
        run: exit 1
